import "./globals.css";
import type { Metadata } from "next";
import { SocketProvider } from "../context/SocketProvider";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat App 1.0",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <>
      <html lang="en">
        <SocketProvider>
          <body className={inter.className}>{children}</body>
        </SocketProvider>
      </html>
    </>
  );
}
